# Generated by Django 5.0.6 on 2024-06-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar_benefits/')),
            ],
            options={
                'verbose_name': 'AR Benefit',
                'verbose_name_plural': 'AR Benefits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ARCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar_case_studies/')),
            ],
            options={
                'verbose_name': 'AR Case Study',
                'verbose_name_plural': 'AR Case Studies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ARFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ar_features/')),
            ],
            options={
                'verbose_name': 'AR Feature',
                'verbose_name_plural': 'AR Features',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blogs/')),
            ],
            options={
                'verbose_name': 'Blogs',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Home_CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home_CaseStudy/')),
            ],
            options={
                'verbose_name': 'Home Case Study',
                'verbose_name_plural': 'Home Case Studies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Home_services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home_services/')),
                ('float_icon', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Home Services',
                'verbose_name_plural': 'Home Services',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='industries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/')),
            ],
            options={
                'verbose_name': 'Industries',
                'verbose_name_plural': 'Industries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('Page_detail_content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_images/')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-id'],
            },
        ),
    ]
