# Generated by Django 4.1 on 2024-06-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_industries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industries',
            options={'ordering': ['title'], 'verbose_name': 'Industries', 'verbose_name_plural': 'Industries'},
        ),
    ]
