# Generated by Django 5.0.6 on 2024-06-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_arbenefit_router_s_arcasestudy_router_s_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arbenefit',
            name='router_s',
        ),
        migrations.RemoveField(
            model_name='arcasestudy',
            name='router_s',
        ),
        migrations.RemoveField(
            model_name='arfeature',
            name='router_s',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='router_s',
        ),
        migrations.RemoveField(
            model_name='home_casestudy',
            name='router_s',
        ),
        migrations.RemoveField(
            model_name='home_services',
            name='router_s',
        ),
        migrations.RemoveField(
            model_name='industries',
            name='router_s',
        ),
        migrations.RemoveField(
            model_name='services',
            name='router_s',
        ),
    ]
