# Generated by Django 5.0.6 on 2024-07-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='location',
            new_name='address',
        ),
    ]
