# Generated by Django 5.0.6 on 2024-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactformsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformsubmission',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
