# Generated by Django 5.0.6 on 2024-07-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={},
        ),
    ]
