# Generated by Django 4.1 on 2024-06-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_leave_status_alter_project_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Attendance Record', 'verbose_name_plural': 'Attendance Records'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['user'], 'verbose_name': 'Employee Profile', 'verbose_name_plural': 'Employee Profiles'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'ordering': ['-start_date'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-date'], 'verbose_name': 'Salary Record', 'verbose_name_plural': 'Salary Records'},
        ),
    ]
